spring:
  server:
    port: 8888
  datasource:
    username: rich
    password: rich2020
    url: jdbc:mysql://47.111.247.251:3306/mybatis_plus?useSSL=false&useUnicode=true&chararterEncoding=utf-8&Timezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl