spring:
  server:
    port: 8888
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:33060/mybatis_plus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev  # 设置项目的开发环境


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 设置日志为控制台输出
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 删除的值为1
      logic-not-delete-value: 0 # 不删除的值为0